# Site settings
title: The flies
email: gaconkzk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a new site that I created for my future work \(-o-)/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theflies.xyz" # the base hostname & protocol for your site
twitter_username: gaconkzk
github_username:  gaconkzk

# Build settings
markdown: kramdown
